### PR TITLE
fixing issue #102

### PR DESCRIPTION
**Pull request by jdehrlich**
Added setup and teardown in testobj and changed single test execution to run the Ztest setup/teardown function if present instead of the suite teardown/setup function

### CODE REVIEW

**Comment by jdehrlich** [comment]
I'm not sure why the test coverage dropped as all of the added lines are tested, but I can add another test to bring up the coverage

**Comment by arpras** [comment]
The coverage monitoring was to monitor more drastic changes or catch significant code addition/change without sufficient unit testing 

However I think you still need to make changes to Ztest to account for my changes that got pulled in at the top. (moving setup/teardown back into Ztest class instead of ztestsuite)

**Comment by arpras** [comment]
Thanks Josh. Merry Christmas and happy new year :)

**Comment by arpras** [comment]
Josh,

I have also created a pull request to merge all changes into zopkio/zopkio from linkedin/zopkio so we can move to zopkio/zopkio as the main branch. Can you please take a look at that ?

**Pull request merged**
